### ISSUE TITLE
Samsung S6 crash [libbypass.so not found]

### ISSUE THREAD

**Issue by fxsalazar** [Uncodin/bypass#190]
``` java
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.gofindit.dubai.vida-1/base.apk"],nativeLibraryDirectories=[/data/app/com.gofindit.dubai.vida-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libbypass.so"
at java.lang.Runtime.loadLibrary(Runtime.java:366)
at java.lang.System.loadLibrary(System.java:988)
at in.uncod.android.bypass.Bypass.<clinit>(Bypass.java:29)
at com.gofindit.core.helper.MarkdownParserUtil.markdownToSpannable(MarkdownParserUtil.java:12)
at com.gofindit.app.magazine.MagazineDetailSectionFragment.onViewCreated(MagazineDetailSectionFragment.java:359)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
```

**Comment by lynfogeek** [comment]
I have a similar error on my Nexus 5 since I updated it to Marshmallow

**Comment by damien5314** [comment]
Strange, native libraries shouldn't disappear from your apk just from updating to a new version of Android... My app using Bypass is still working on my Nexus 5 after upgrading.

@fxsalazar You'll probably need to include more context to the issue, that error basically just says the native lib is missing from your app entirely. Was it working before, and then stopped?

**Comment by fxsalazar** [comment]
Sorry for not putting more context on it. But, basically it just doesn't work only on that phone. I did many tests in many other different vendors and Android versions and it just works (I used an Galaxy Note with Android 5.1.1, same as the S6 and it worked); now with the @lynfogeek new info, I'm not really sure what it could be.

**Comment by fxsalazar** [comment]
Today we did a test with the Galaxy Edge and it crash as well but also we have a Nexus 5 with fresh new Marshmallow and it worked fine.

**Comment by ZakTaccardi** [comment]
This issue may be related to a buggy android gradle plugin. Which version are you using?
